--------------------------------------------------------
--  File created - Wednesday-October-05-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUYER
--------------------------------------------------------

  CREATE TABLE "S26913224"."BUYER" 
   (	"BUYER_ID" NUMBER(*,0), 
	"BUYER_FNAME" VARCHAR2(20 BYTE), 
	"BUYER_LNAME" VARCHAR2(20 BYTE), 
	"BUYER_ADDRESS" VARCHAR2(50 BYTE), 
	"BUYER_SUBURB" VARCHAR2(30 BYTE), 
	"BUYER_STATE" CHAR(3 BYTE), 
	"BUYER_PHONE" CHAR(10 BYTE), 
	"BUYER_MOBILE" CHAR(10 BYTE), 
	"BUYER_EMAIL" VARCHAR2(60 BYTE), 
	"BUYER_MAILING" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FEATURE
--------------------------------------------------------

  CREATE TABLE "S26913224"."FEATURE" 
   (	"FEATURE_ID" NUMBER(*,0), 
	"FEATURE_NAME" VARCHAR2(30 BYTE), 
	"FEATURE_DESC" VARCHAR2(250 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LISTING
--------------------------------------------------------

  CREATE TABLE "S26913224"."LISTING" 
   (	"LISTING_ID" NUMBER(*,0), 
	"SELLER_ID" NUMBER(*,0), 
	"PROPERTY_ID" NUMBER(*,0), 
	"LISTING_DESC" VARCHAR2(1000 BYTE), 
	"LISTING_DATE" DATE, 
	"LISTING_PRICE" NUMBER(*,0), 
	"SALE_DATE" DATE, 
	"SALE_PRICE" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PICTURE
--------------------------------------------------------

  CREATE TABLE "S26913224"."PICTURE" 
   (	"PIC_ID" NUMBER(*,0), 
	"PIC_NAME" VARCHAR2(100 BYTE), 
	"PROPERTY_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROPERTY
--------------------------------------------------------

  CREATE TABLE "S26913224"."PROPERTY" 
   (	"PROPERTY_ID" NUMBER(*,0), 
	"PROPERTY_ADDRESS" VARCHAR2(50 BYTE), 
	"PROPERTY_SUBURB" VARCHAR2(30 BYTE), 
	"TYPE_ID" NUMBER(*,0), 
	"PROPERTY_BEDROOMS" NUMBER(*,0), 
	"PROPERTY_BATHROOMS" NUMBER(*,0), 
	"PROPERTY_CARPARKS" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROPERTYFEATURE
--------------------------------------------------------

  CREATE TABLE "S26913224"."PROPERTYFEATURE" 
   (	"PROPERTY_ID" NUMBER(*,0), 
	"FEATURE_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROPERTYTYPE
--------------------------------------------------------

  CREATE TABLE "S26913224"."PROPERTYTYPE" 
   (	"TYPE_ID" NUMBER(*,0), 
	"TYPE_NAME" VARCHAR2(30 BYTE), 
	"TYPE_DESC" VARCHAR2(150 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SELLER
--------------------------------------------------------

  CREATE TABLE "S26913224"."SELLER" 
   (	"SELLER_ID" NUMBER(*,0), 
	"SELLER_FNAME" VARCHAR2(20 BYTE), 
	"SELLER_LNAME" VARCHAR2(20 BYTE), 
	"SELLER_ADDRESS" VARCHAR2(50 BYTE), 
	"SELLER_SUBURB" VARCHAR2(30 BYTE), 
	"SELLER_STATE" CHAR(3 BYTE), 
	"SELLER_PHONE" CHAR(10 BYTE), 
	"SELLER_MOBILE" CHAR(10 BYTE), 
	"SELLER_EMAIL" VARCHAR2(60 BYTE), 
	"SELLER_MAILING" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into S26913224.BUYER
SET DEFINE OFF;
Insert into S26913224.BUYER (BUYER_ID,BUYER_FNAME,BUYER_LNAME,BUYER_ADDRESS,BUYER_SUBURB,BUYER_STATE,BUYER_PHONE,BUYER_MOBILE,BUYER_EMAIL,BUYER_MAILING) values (1,'Lena','Oxton','6 Speedy Lane','Ormond','VIC',null,'0436454656','loxton@omail.com','Y');
Insert into S26913224.BUYER (BUYER_ID,BUYER_FNAME,BUYER_LNAME,BUYER_ADDRESS,BUYER_SUBURB,BUYER_STATE,BUYER_PHONE,BUYER_MOBILE,BUYER_EMAIL,BUYER_MAILING) values (2,'Jamison','Fawkes','51 Rough Street','Frankston','VIC','0387569887',null,'jfawkes@omail.com','N');
Insert into S26913224.BUYER (BUYER_ID,BUYER_FNAME,BUYER_LNAME,BUYER_ADDRESS,BUYER_SUBURB,BUYER_STATE,BUYER_PHONE,BUYER_MOBILE,BUYER_EMAIL,BUYER_MAILING) values (3,'Mei-Ling','Zhou','3/64 Frosty Drive','North Melbourne','VIC',null,'0498561324','mzhou@omail.com','Y');
Insert into S26913224.BUYER (BUYER_ID,BUYER_FNAME,BUYER_LNAME,BUYER_ADDRESS,BUYER_SUBURB,BUYER_STATE,BUYER_PHONE,BUYER_MOBILE,BUYER_EMAIL,BUYER_MAILING) values (4,'Amelie','Lacroix','2 Scope Street','Bentleigh','VIC',null,'0498565678','alacroix@omail.com','Y');
Insert into S26913224.BUYER (BUYER_ID,BUYER_FNAME,BUYER_LNAME,BUYER_ADDRESS,BUYER_SUBURB,BUYER_STATE,BUYER_PHONE,BUYER_MOBILE,BUYER_EMAIL,BUYER_MAILING) values (5,'Mako','Rutledge','51 Rough Street','Frankston','VIC','0387569887',null,'mrutledge@omail.com','Y');
Insert into S26913224.BUYER (BUYER_ID,BUYER_FNAME,BUYER_LNAME,BUYER_ADDRESS,BUYER_SUBURB,BUYER_STATE,BUYER_PHONE,BUYER_MOBILE,BUYER_EMAIL,BUYER_MAILING) values (6,'Markus','Makers','11 Road Street','Frankston','VIC','0398565151',null,'makeme@gmail.com','Y');
Insert into S26913224.BUYER (BUYER_ID,BUYER_FNAME,BUYER_LNAME,BUYER_ADDRESS,BUYER_SUBURB,BUYER_STATE,BUYER_PHONE,BUYER_MOBILE,BUYER_EMAIL,BUYER_MAILING) values (7,'Fisherman','Phil','13 Ocean Way','Black Rock','VIC',null,'0436785454','atchme@mail.com','Y');
Insert into S26913224.BUYER (BUYER_ID,BUYER_FNAME,BUYER_LNAME,BUYER_ADDRESS,BUYER_SUBURB,BUYER_STATE,BUYER_PHONE,BUYER_MOBILE,BUYER_EMAIL,BUYER_MAILING) values (8,'Sheldon','Scully','64 Street Parade','Brunswick','VIC','0398765454',null,'scullboi@omail.com','Y');
Insert into S26913224.BUYER (BUYER_ID,BUYER_FNAME,BUYER_LNAME,BUYER_ADDRESS,BUYER_SUBURB,BUYER_STATE,BUYER_PHONE,BUYER_MOBILE,BUYER_EMAIL,BUYER_MAILING) values (9,'Barry','Bartledge','123 High Road','Bacchus March','VIC','0398321654',null,'bazzaaa@pmail.com','Y');
Insert into S26913224.BUYER (BUYER_ID,BUYER_FNAME,BUYER_LNAME,BUYER_ADDRESS,BUYER_SUBURB,BUYER_STATE,BUYER_PHONE,BUYER_MOBILE,BUYER_EMAIL,BUYER_MAILING) values (10,'Thomas','Tankeng','51 Sodor Avenue','Clayton','VIC',null,'0487565323','peeppeep@smail.com','Y');
REM INSERTING into S26913224.FEATURE
SET DEFINE OFF;
Insert into S26913224.FEATURE (FEATURE_ID,FEATURE_NAME,FEATURE_DESC) values (1,'Tennis Court','A large court for playing tennis');
Insert into S26913224.FEATURE (FEATURE_ID,FEATURE_NAME,FEATURE_DESC) values (2,'Swimming Pool - Above Ground','An above-ground pool for swimming in');
Insert into S26913224.FEATURE (FEATURE_ID,FEATURE_NAME,FEATURE_DESC) values (3,'Swimming Pool - Below Ground','A below-ground pool for swimming in');
Insert into S26913224.FEATURE (FEATURE_ID,FEATURE_NAME,FEATURE_DESC) values (4,'Wine Cellar','A specialised room for storing wine');
Insert into S26913224.FEATURE (FEATURE_ID,FEATURE_NAME,FEATURE_DESC) values (5,'Helipad','A landing pad for helicopters');
Insert into S26913224.FEATURE (FEATURE_ID,FEATURE_NAME,FEATURE_DESC) values (6,'Showroom','An open room for displaying items to customers');
REM INSERTING into S26913224.LISTING
SET DEFINE OFF;
REM INSERTING into S26913224.PICTURE
SET DEFINE OFF;
REM INSERTING into S26913224.PROPERTY
SET DEFINE OFF;
REM INSERTING into S26913224.PROPERTYFEATURE
SET DEFINE OFF;
REM INSERTING into S26913224.PROPERTYTYPE
SET DEFINE OFF;
Insert into S26913224.PROPERTYTYPE (TYPE_ID,TYPE_NAME,TYPE_DESC) values (1,'House','A house in a residential area.');
Insert into S26913224.PROPERTYTYPE (TYPE_ID,TYPE_NAME,TYPE_DESC) values (2,'Apartment','An apartment in a residential area.');
Insert into S26913224.PROPERTYTYPE (TYPE_ID,TYPE_NAME,TYPE_DESC) values (3,'Shop','A shopfront in a commercial area.');
Insert into S26913224.PROPERTYTYPE (TYPE_ID,TYPE_NAME,TYPE_DESC) values (4,'Factory','A factory in an industrial area.');
Insert into S26913224.PROPERTYTYPE (TYPE_ID,TYPE_NAME,TYPE_DESC) values (5,'Warehouse','A warehouse in an industrial area.');
REM INSERTING into S26913224.SELLER
SET DEFINE OFF;
Insert into S26913224.SELLER (SELLER_ID,SELLER_FNAME,SELLER_LNAME,SELLER_ADDRESS,SELLER_SUBURB,SELLER_STATE,SELLER_PHONE,SELLER_MOBILE,SELLER_EMAIL,SELLER_MAILING) values (1,'Jack','Morrison','1 Soldier Lane','Clayton','VIC','0123456789',null,'jmorrison@omail.com','Y');
Insert into S26913224.SELLER (SELLER_ID,SELLER_FNAME,SELLER_LNAME,SELLER_ADDRESS,SELLER_SUBURB,SELLER_STATE,SELLER_PHONE,SELLER_MOBILE,SELLER_EMAIL,SELLER_MAILING) values (2,'Hanzo','Shimada','4/23 Center Road','Ormond','VIC',null,'0234567891','hshimada@omail.com','Y');
Insert into S26913224.SELLER (SELLER_ID,SELLER_FNAME,SELLER_LNAME,SELLER_ADDRESS,SELLER_SUBURB,SELLER_STATE,SELLER_PHONE,SELLER_MOBILE,SELLER_EMAIL,SELLER_MAILING) values (3,'Lucio','Santos','63 Jammin Street','Bentleigh','VIC',null,null,'lsantos@omail.com','N');
Insert into S26913224.SELLER (SELLER_ID,SELLER_FNAME,SELLER_LNAME,SELLER_ADDRESS,SELLER_SUBURB,SELLER_STATE,SELLER_PHONE,SELLER_MOBILE,SELLER_EMAIL,SELLER_MAILING) values (4,'Jesse','McCree','39 Cowboy Parade','Braeside','VIC',null,'0434123876','jmcree@omail.com','Y');
Insert into S26913224.SELLER (SELLER_ID,SELLER_FNAME,SELLER_LNAME,SELLER_ADDRESS,SELLER_SUBURB,SELLER_STATE,SELLER_PHONE,SELLER_MOBILE,SELLER_EMAIL,SELLER_MAILING) values (5,'Gabriel','Reyes','420 Edgy Road','Brighton','VIC','0398765432',null,'greyes@omail.com','N');
Insert into S26913224.SELLER (SELLER_ID,SELLER_FNAME,SELLER_LNAME,SELLER_ADDRESS,SELLER_SUBURB,SELLER_STATE,SELLER_PHONE,SELLER_MOBILE,SELLER_EMAIL,SELLER_MAILING) values (6,'Billy','Bob','9 Country Avenue','Frankston','VIC','0394587878',null,'bbobboy@mail.com','Y');
Insert into S26913224.SELLER (SELLER_ID,SELLER_FNAME,SELLER_LNAME,SELLER_ADDRESS,SELLER_SUBURB,SELLER_STATE,SELLER_PHONE,SELLER_MOBILE,SELLER_EMAIL,SELLER_MAILING) values (7,'Jimbles','Jambles','73 Road Street','Brighton East','VIC','0398765432',null,'jjjam@hotmail.com','Y');
Insert into S26913224.SELLER (SELLER_ID,SELLER_FNAME,SELLER_LNAME,SELLER_ADDRESS,SELLER_SUBURB,SELLER_STATE,SELLER_PHONE,SELLER_MOBILE,SELLER_EMAIL,SELLER_MAILING) values (8,'Gabby','Redd','5 Secret Parade','Toorak','VIC',null,'0487112665','gredd@mail.com','N');
Insert into S26913224.SELLER (SELLER_ID,SELLER_FNAME,SELLER_LNAME,SELLER_ADDRESS,SELLER_SUBURB,SELLER_STATE,SELLER_PHONE,SELLER_MOBILE,SELLER_EMAIL,SELLER_MAILING) values (9,'Darcie','Swan','23 Fancy Way','Brunswick','VIC','0398987878',null,'dstft@gmail.com','Y');
Insert into S26913224.SELLER (SELLER_ID,SELLER_FNAME,SELLER_LNAME,SELLER_ADDRESS,SELLER_SUBURB,SELLER_STATE,SELLER_PHONE,SELLER_MOBILE,SELLER_EMAIL,SELLER_MAILING) values (10,'Mitch','Whales','23 Fancy Way','Brunswick','VIC','0398987878',null,'dstft2@gmail.com','Y');
